-- DML -> DATA MANIPULATION LANGUAGE
INSERT , WHERE E DELETE 

-- DDL -> DATA DEFINITION LANGUAGEM
CREATE TABLE EXEMPLO(
  EXEMPLO VARCHAR(20)  
);

ALTER TABLE EXEMPLO
CHANGE PREO VALOR_UNITARIO INT NOT NULL;

ALTER TABLE EXEMPLO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL; 

ALTER TABLE EXEMPLO
ADD PESO FLOAT(10, 2) NOT NULL;

ALTER TABLE EXEMPLO
DROP COLUMN PESO;

ALTER TABLE EXEMPLO
ADD COLUMN PESO FLOAT(10, 2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE EXEMPLO
ADD COLUMN PESO FLOAT(10, 2) NOT NULL
FIRST;
-- DCL -> DATA CONTROL LANGUAGE
-- TCL -> TRANSACTION CONTROL LANGUAGEM