SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO

SELECT NOME,
CAST(DAY(NASCIMENTO) AS VARCHAR) 
+ '/' + 
CAST(MONTH(NASCIMENTO) AS VARCHAR)
+ '/' +
CAST(YEAR(NASCIMENTO) AS VARCHAR) AS "NASCIMENTO"
FROM ALUNO