CREATE TABLE PRODUTOS(
    IDPRODUTO INT PRIMARY KEY IDENTITY,
    NOME VARCHAR(50) NOT NULL,
    CATEGORIA VARCHAR(30) NOT NULL,
    PRECO NUMERIC(10, 2) NOT NULL
)
GO

CREATE TABLE HISTORICO(
    IDOPERACAO INT PRIMARY KEY IDENTITY,
    PRODUTO VARCHAR(50) NOT NULL,
    CATEGORIA VARCHAR(30) NOT NULL,
    PRECOANTIGO NUMERIC(10, 2) NOT NULL,
    PRECONOVO NUMERIC(10, 2) NOT NULL,
    DATA DATETIME,
    USUARIO VARCHAR(30),
    MENSAGEM VARCHAR(100)
)
GO

INSERT INTO PRODUTOS VALUE('LIVRO SQL SERVER', 'LIVROS', 98.00)
INSERT INTO PRODUTOS VALUE('KIT ARDUINO STARTER', 'HARDWARE', 158.00)
INSERT INTO PRODUTOS VALUE('RESISTOR 220 HOMS 30X', 'HARDWARE', 38.00)
INSERT INTO PRODUTOS VALUE('ADOBE ACROBAT LICENSE 1 YEAR', 'SOFTWARE', 98.00)
GO

SELECT * FROM PRODUTOS
SELECT * FROM HISTORICO

SELECT SUSER_NAME()
GO

CREATE TRIGGER TRG_ATUALIZA_PRECO
ON DBO.PRODUTOS
FOR UPDATE AS
IF UPDATE(PRECO) -- tsql
BEGIN

    DECLARE @IDPRODUTO INT
    DECLARE @PRODUTO VARCHAR(30)
    DECLARE @CATEGORIA VARCHAR(10)
    DECLARE @PRECO_ANTIGO NUMERIC(10, 2)
    DECLARE @PRECONOVO NUMERIC(10, 2)
    DECLARE @DATA DATETIME
    DECLARE @USUARIO VARCHAR(30)
    DECLARE @ACAO VARCHAR(100)

    SELECT @IDPRODUTO = IDPRODUTO FROM inserted
    SELECT @PRODUTO = NOME FROM inserted
    SELECT @CATEGORIA = CATEGORIA FROM inserted
    SELECT @PRECO = PRECO FROM deleted
    SELECT @PRECONOVO = PRECO FROM inserted
    
    SET @DATA = GETDATE()
    SET @USUARIO = SUSER_NAME()
    SET @ACAO = "VALOR INSERIDO PELO TRIGGER TRG_ATUALIZA_PRECO"

    INSERT INTO HISTORICO 
    (PRODUTO, CATEGORIA, PRECOANTIGO, PRECONOVO, DATA, USUARIO, MENSAGEM)
    VALUES
    (@PRODUTO, @CATEGORIA, @PRECO, @PRECONOVO, @DATA, @USUARIO, @ACAO)

    PRINT 'TRIGGER REALIZADA COM SUCESSO'
END
GO

UPDATE PRODUTOS SET PRECO = 100.00
WHERE IDPRODUTO = 2
GO