CREATE TABLE RESULTADO(
    IDRESULTADO INT PRIMARY KEY IDENTITY,
    RESULTADO INT
)
GO

DECLARE
    @RESULTADO INT
    SET @RESULTADO = (SELECT 50 + 50)
    INSERT INTO RESULTADO VALUES(@RESULTADO)
GO

DECLARE
    @RESULTADO INT
    SET @RESULTADO = (SELECT 50 + 50)
    INSERT INTO RESULTADO VALUES(@RESULTADO)
    PRINT 'VALOR INSERIDO NA TABELA: ' + CAST(@RESULTADO AS VARCHAR)
GO

CREATE TABLE EMPREGADO(
    IDEMPREGADO INT PRIMARY KEY,
    NOME VARCHAR(50),
    SALARIO MONEY,
    IDGERENTE INT
)
GO

ALTER TABLE EMPREGADO ADD CONSTRAINT FK_GERENTE
FOREIGN KEY(IDGERENTE) REFERENCES EMPREGADO(IDEMPREGADO)


INSERT INTO EMPREGADO VALUES(1, 'CLARA', 5000.00, NULL)
INSERT INTO EMPREGADO VALUES(1, 'CLARA', 3700.00, 1)
INSERT INTO EMPREGADO VALUES(1, 'CLARA', 3700.00, 1)
GO

CREATE TABLE HIST_SALARIO(
    IDEMPREGADO INT,
    ANTIGO_SAL MONEY,
    NOVO_SAL MONEY
    DATA DATETIME
)
GO

CREATE TRIGGER TG_SALARIO
ON DBO.EMPREGADO
FOR UPDATE AS
IF UPDATE(SALARIO)
BEGIN
    INSERT INTO HIST_SALARIO
    (IDEMPREGADO, ANTIGO_SAL, NOVO_SAL, DATA)
    SELECT D.IDEMPREGADO, D.SALARIO, I.SALARIO, GETDATE()
    FROM DELETED D, INSERTED I
    WHERE D.IDEMPREGADO = I.IDEMPREGADO
END
GO

UPDATE EMPREGADO SET SALARIO = SALARIO * 1.1
GO





