CREATE TABLE SALARIO_RANGE(
    MINSAL MONEY,
    MAXSAL MONEY
)
GO

INSERT INTO SALARIO_RANGE VALUES(3000.00, 6000.00)
GO

CREATE TRIGGER TG_RANGE
ON DBO.EMPREGADO
FROM INSERT, UPDATE
AS
    DECLARE
        @MINSAL MONEY
        @MAXSAL MONEY
        @ATUALSAL MONEY

    SELECT @MINSAL = MINSAL, @MAXSAL = MAXSAL FROM SALARIO_RANGE

    SELECT @ATUALSAL = I.SALARIO
    FROM INSERTED I

    IF(@ATUALSAL < @MINSAL)
    BEGIN
        RAISERROR("SALARIO MENOR QUE O PISO", 16, 1)
        ROLLBACK TRANSACTION
    END

    IF(@ATUALSAL > @MAXSAL)
    BEGIN
        RAISERROR("SALARIO MAIOR QUE O TETO", 16, 1)
        ROLLBACK TRANSACTION
    END
GO

SP_HELPTEXT TG_RANGE
GO




