DELIMITER #

STATUS

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), P_HORAS INT(3), P_PRECO FLOAT(10,2))
BEGIN
    INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);
END
#

DELIMITER ;

CALL CAD_CURSO(PYTHON BASICO, 35, 450);

-- EXERCICIO

DELIMITER #

CREATE PROCEDURE CONSULTA_CURSO()
BEGIN
    SELECT IDCURSO, NOME, HORAS, PRECO FROM CURSOS;
END
#

DELIMITER ;
