CREATE TABLE LANCAMENTO_CONTABIL(
    CONTA INT,
    VALOR INT,
    DEB_CRED CHAR(1)
)
GO

SELECT * FROM LANCAMENTO_CONTABIL
GO
-- \t = TAB \n = ENTER
BULK INSERT LANCAMENTO_CONTABIL
FROM 'CONTAS.txt'
WITH(
    FIRST ROW = 2,
    DATAFILETYPE = 'CHAR',
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '\n' 
)
GO

SELECT * FROM LANCAMENTO_CONTABIL