CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTOS(
    IDPRODUTO INT PRYMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    VALOR FLOAT(10,2)
);

STATUS;

CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTOS(
    IDBKP INT PRYMARY KEY AUTO_INCREMENT,
    IDPRODUTO INT,
    NOME VARCHAR(30),
    VALOR FLOAT(10,2)
);

USE LOJA;

INSERT INTO BACKUP.BKP_PRODUTOS VALUES (NULL, 1000, 'TESTE', 0.0);

DELIMITER $

CREATE TRIGGER BACKUP_PRODUTOS
BEFORE INSERT ON PRODUTOS
FOR EACH ROW
BEGIN

    INSERT INTO BACKUP.BKP_PRODUTOS VALUES (NULL, NEW.IDPRODUTO, NEW.NOME, NEW.PRECO);

END $

DELIMITER ;

DELIMITER $

CREATE TRIGGER BACKUP_PRODUTOS
after INSERT ON PRODUTOS
FOR EACH ROW
BEGIN

    INSERT INTO BACKUP.BKP_PRODUTOS VALUES (NULL, NEW.IDPRODUTO, NEW.NOME, NEW.PRECO);

END $

DELIMITER ;

ALTER TABLE BACKUP.BKP_PRODUTOS
ADD EVENTO CHAR(1);

DROP TRIGGER BACKUP_PRODUTOS

DELIMITER $

CREATE TRIGGER BACKUP_PRODUTOS_DEL
BEFORE DELETE ON PRODUTOS
FOR EACH ROW
BEGIN

    INSERT INTO BACKUP.BKP_PRODUTOS VALUES (NULL, OLD.IDPRODUTO, OLD.NOME, OLD.PRECO, 'D');

END $

DELIMITER ;