CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    VALOR FLOAT(10, 2)
);

INSERT INTO PRODUTO  VALUES(NULL, "LIVRO MODELAGEM I", 50.00);
INSERT INTO PRODUTO  VALUES(NULL, "LIVRO MODELAGEM II", 50.00);
INSERT INTO PRODUTO  VALUES(NULL, "LIVRO POWER BI", 70.00);
INSERT INTO PRODUTO  VALUES(NULL, "LIVRO ORACLE", 90.00);
INSERT INTO PRODUTO  VALUES(NULL, "LIVRO JAVASCRIPT,HTML E CSS", 45.00);

CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
    IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
    IDPRODUTO INT,
    NOME VARCHAR(30),
    VALOR_ORIGINAL FLOAT(10, 2),
    VALOR_ALTERADO FLOAT(10, 2),
    DATA DATETIME,
    USUARIO VARCHAR(30),
    EVENTO CHAR(1)
);

-- QUANDO
SELECT NOW();
-- QUEM
SELECT CURRENT_USER();

DELIMITER $

CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN 

    INSERT INTO BACKUP.BKP_PRODUTO VALUES
    (NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, NEW.VALOR, NOW(), CURRENT_USER(), 'U');

END
$

DELIMITER ;