-- contando os registros da tabela
SELECT COUNT(*) FROM cliente;

-- Operador GROUP BY 

SELECT SEXO, COUNT(*) FROM cliente
GROUP BY SEXO;

-- /* PERFORMANCE EM OPERADORES LOGICOS */

-- /* 1 MILHAO DE REGISTROS

-- PARA CONTAR
-- SELECT COUNT(*) FROM CLIENTE;

-- SELECT SEXO, COUNT(*) FROM CLIENTE
-- GROUP BY SEXO;

-- SELECT CIDADE, COUNT(*) FROM CLIENTE
-- GROUP BY CIDADE;

-- CONDICAO
-- SEXO = F
-- CIDADE = RIO DE JANEIRO

-- SITUACAO - TRATANDO COM OU / OR
-- 70% MULHERES = SEXO = F
-- 30% MORA NO RIO DE JANEIRO

-- SELECT NOME, SEXO, ENDERECO
-- FROM CLIENTE
-- WHERE SEXO = 'F'
-- OR CIDADE = 'RIO DE JANEIRO';

-- SITUACAO - TRATANDO COM E / AND
-- 70% MULHERES = SEXO = F
-- 30% MORA NO RIO DE JANEIRO

-- SELECT NOME, SEXO, ENDERECO
-- FROM CLIENTE
-- WHERE CIDADE = 'RIO DE JANEIRO'
-- AND SEXO = 'F';