INSERT  INTO  cliente(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('ANDRESA', 'F', 'RUA DAS PALMEIRAS - TIJUCA - RIO DE JANEIRO - RJ', '936647253', 735375634);
-- Comando SELECT 
    -- SELECAO, CONJUCAO e JUNCAO
SELECT NOW() AS DATA_HORA;
SELECT  'Felipe Mafra';
SELECT 'Banco de dados';

-- ALIAS de colunas

SELECT NOME, SEXO, EMAIL FROM cliente;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM cliente; 

-- Apenas para fins academicos
SELECT * FROM cliente;