-- Criaçao do BD
CREATE DATABASE LIVRARIA;
SHOW DATABASES; 
-- USA O BD LIVRARIA
USE LIVRARIA;
-- CRIA A TABELA LIVROS
CREATE TABLE LIVROS(
    NOME_LIVRO VARCHAR(100),
    NOME_AUTOR VARCHAR (50),
    SEXO_AUTOR CHAR(1) NOT NULL,
    NUMERO_PAGINAS CHAR (4),
    NOME_EDITORA VARCHAR (100),
    VALOR_LIVRO DOUBLE (10,2) NOT NULL,
    ESTADO_EDITORA CHAR (2),
    ANO_PUBLICACAO CHAR (10)
);
DESC LIVROS;

-- Colocando os dados no DATABASE Livros
-- INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
-- VALUES();

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('Cavaleiro Real', 'Ana Claudia', 'F', 465, 'Atlas', 49.90, 'RJ', '2009');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('SQL para Leigos', 'João Nunes', 'M', 450, 'Addison', 98, 'SP', '2018');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('Receitas Caseiras', 'Celia Tavares', 'F', 210, 'Atlas', 45, 'RJ', '2018');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', '2008');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('Habitos Saudaveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', '2019');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Bubba', 60, 'MG', '2016');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('Estácio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100, 'ES', '2015');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('Pra Sempre Amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98,'ES', '2011');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('Copas Inesqueciveis', 'Marcos Alcantara', 'M', 200, 'Larson', 130.98, 'RS', '2018');

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO) 
VALUES('O Poder da Mente', 'Clara Mafra', 'F', 120, 'Continental', 50.98, 'SP', '2017');

-- Verificando a tabela LIVROS

SELECT NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO
FROM LIVROS;

STATUS;