DECLARE
    @NUMERO INT = 5
BEGIN
    IF @NUMERO = 5
        PRINT 'O VALOR É VERDADEIRO'
    ELSE
        PRINT 'O VALOR É FALSO'
END
GO

DECLARE
    @CONTADOR INT
BEGIN
    SELECT
    CASE
        WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
        WHEN FABRICANTE = 'RENAULT' THEN 'FAIXA 2'
        WHEN FABRICANTE = 'VOLKSWAGEN' THEN 'FAIXA 3'
        ELSE 'OUTRAS FAIXAS'
    END AS "INFORMACOES",
    *
    FROM CARROS
END
GO
