BEGIN
    PRINT 'PRIMEIRO sBLOCO'
END
GO

DECLARE
    @CONTADOR INT
BEGIN 
    SET @CONTADOR = 5
    PRINT @CONTADOR
END 
GO

DECLARE
    @V_NUMERO NUMERIC(10, 2) = 100.52,
    @V_DATA DATETIME = '20170207'
BEGIN
    PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
    PRINT 'vALOR NUMERICO: ' + CONVERT(VARCHAR, @V_DATA, 121) -- MAIS USADO PARA DATAS
    PRINT 'vALOR NUMERICO: ' + CONVERT(VARCHAR, @V_DATA, 120) -- MAIS USADO PARA DATAS
    PRINT 'vALOR NUMERICO: ' + CONVERT(VARCHAR, @V_DATA, 105) -- MAIS USADO PARA DATAS
END
GO

