CREATE TABLE CARROS(
    CARRO VARCHAR(20),
    FABRICANTE VARCHAR(30)
)
GO

INSERT INTO CARROSVALUES('KA', 'FORD')
INSERT INTO CARROSVALUES('FIESTA', 'FORD')
INSERT INTO CARROSVALUES('CLIO', 'RENAULT')
INSERT INTO CARROSVALUES('DOBLO', 'FIAT')
INSERT INTO CARROSVALUES('PRISMA', 'FORD')
INSERT INTO CARROSVALUES('SANDERO', 'RENAULT')
INSERT INTO CARROSVALUES('GOL', 'VOLKSWAGEN')

DECLARE
    @V_CONT_FORD INT,
    @V_CONT_RENAULT INT 
BEGIN
    SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS
    WHERE FABRICANTE = 'FORD')
    PRINT 'QUANTIDADE FORD: ' + CAST(@V_CONT_FORD AS VARCHAR)

    SELECT @V_CONT_RENAULT = COUNT(*) FROM CARROS  WHERE FABRICANTE = 'RENAULT'
    PRINT =  'QUANTIDADE RENAULT: ' = CAST(@V_CONT_RENAULT AS VARCHAR)
END
GO