CREATE TABLE PESSOA(
    IDPESSOA INT PRIMARY KEY IDENTITY,
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M','F')),
    NASCIMENTO DATE NOT NULL
)
GO

CRETE TABLE TELEFONE(
    IDTELEFONE INT NOT NULL IDENTITY,
    TIPO CHAR(3) NOT NULL CHECK(TIPO IN ('CEL','COM','RES')),
    NUMERO CHAR(10) NOT NULL,
    ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PESSOA 
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO', 'M', '1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL', 'M', '2000-09-24')
INSERT INTO PESSOA VALUES('CLEIDE', 'F', '1998-04-03')

INSERT INTO TELEFONE VALUES('CEL', '1084563782', 1)
INSERT INTO TELEFONE VALUES('COM', '1084563782', 2)
INSERT INTO TELEFONE VALUES('RES', '1084563782', 3)

CREATE PROC SOMA
AS
    SELECT 10 + 10 AS SOMA
GO

SOMA
-- OU
EXEC SOMA
GO

CREATE PROC CONTA @NUM1 INT, @NUM2 INT
AS
    SELECT @NUM1 + @NUM2 AS RESULTADO
GO

EXEC SONTA 90, 78
GO

DROP PROC CONTA
GO

SELECT NOME, NUMERO
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

CREATE PROC TELEFONES @TIPO CHAR(3)
AS
    SELECT NOME, NUMERO
    INNER JOIN TELEFONE
    ON IDPESSOA = ID_PESSOA
    WHERE TIPO = @TIPO
GO

EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO

EXEC TELEFONES 'RES'
GO

CREATE PROC GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
    SELECT @CONTADOR = COUNT(*)
    FROM TELEFONE
    WHERE TIPO = @TIPO
GO

DECLARE @SAIDA INT
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

DECLARE @SAIDA INT
EXEC GETTIPO 'CEL', @SAIDA OUTPUT
SELECT @SAIDA
GO