CREATE PROC CADASTRO @NOME VARCHAR(30),@SEXO CHAR(1), NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
    DECLARE @FK INT
    INSERT INTO PESSOA VALUES(@NOME, @SEXO, @NASCIMENTO)

    SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)

    INSERT INTO TELEFONE VALUES(@IPO, @NUMERO, @FK)
GO

CADASTRO 'JORGE', 'M', '1981-01-01', 'CEL', '9127456378'
GO

SELECT 