CREATE DATABASE CURSORES;

USE CURSORES;

CRETAE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL, 'MAFRA', 32432, 73527, 21334);
INSERT INTO VENDEDORES VALUES(NULL, 'LUIZA', 74548, 54753, 63374);
INSERT INTO VENDEDORES VALUES(NULL, 'MAICON', 54753, 32552, 32432);
INSERT INTO VENDEDORES VALUES(NULL, 'MARILIA', 21334, 21334, 74548);
INSERT INTO VENDEDORES VALUES(NULL, 'LUCAS', 32552, 54753, 86432);
INSERT INTO VENDEDORES VALUES(NULL, 'MANDREA', 86432, 54753, 21334);

SELECT NOME, (JAN+FEV+MAR) AS TOTAL, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN

    DECLARE FIM INT DEFAULT 0;
    DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
    DECLARE VNOME VARCHAR(50);

    DECLARE REG CURSOR FOR(
        SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
    );

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

    OPEN REG;

        REPEAT 

            FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
            IF NOT FIM theatlantic
                
                SET VTOTAL = VAR1 + VAR2 + VAR3;
                SET VMEDIA = VTOTAL / 3;

                INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
            END IF
        UNTIL FIM END REPEAT;

    CLOSE REG;

END
$

DELIMITER ;

CALL INSEREDADOS();