SELECT * FROM  CLIENTE
ORDER BY IDCLIENTE;
SELECT * FROM  CLIENTE
ORDER BY 1;

SELECT * FROM  CLIENTE
ORDER BY 2;

SELECT * FROM  CLIENTE
ORDER BY IDCLIENTE, SEXO;

SELECT NOME FROM  CLIENTE
ORDER BY 1,2;

SELECT NOME FROM  CLIENTE
ORDER BY IDCLIENTE, NOME;

SELECT * FROM  CLIENTE
ORDER BY 1 ASC;

SELECT * FROM  CLIENTE
ORDER BY 1 DESC;
