CREATE VIEW RELATORIO AS
SELECT 
    C.NOME, 
    C.SEXO, 
    IFNULL(C.EMAIL, '**********') AS EMAIL, 
    T.TIPO, 
    T.NUMERO, 
    E.BAIRRO, 
    E.CIDADE, 
    E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT * FROM RELATORIO;

DESC RELATORIO;

DROP VIEW RELATORIO;

CREATE VIEW V_RELATORIO AS
SELECT 
    C.NOME, 
    C.SEXO, 
    IFNULL(C.EMAIL, '**********') AS EMAIL, 
    T.TIPO, 
    T.NUMERO, 
    E.BAIRRO, 
    E.CIDADE, 
    E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;